### ISSUE TITLE
Errors on events

### ISSUE THREAD

**Issue by lurk24** [TimelessMC/Afterlife#2]
I want to try to use this plugin but i see errors on the console when certain events occur such as when i attack a mob, here is an example:

```
19:31:46 [FATAL] Could not pass event "cn.nukkit.event.entity.EntityDamageByEntityEvent" to "AfterLife v2.2.1": null on com.steve.nukkit.AfterLife.events.CustomEvent  
19:31:46 [ERROR] Throwing                                                                                                                                              
cn.nukkit.utils.EventException: null                                                                                                                                   
        at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:34) ~[nukkit-1.0-SNAPSHOT.jar:?]                                                      
        at cn.nukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:56) ~[nukkit-1.0-SNAPSHOT.jar:?]                                                      
        at cn.nukkit.plugin.PluginManager.callEvent(PluginManager.java:546) ~[nukkit-1.0-SNAPSHOT.jar:?]                                                               
        at cn.nukkit.entity.Entity.attack(Entity.java:1018) ~[nukkit-1.0-SNAPSHOT.jar:?]                                                                               
        at cn.nukkit.entity.EntityLiving.attack(EntityLiving.java:113) ~[nukkit-1.0-SNAPSHOT.jar:?]                                                                    
        at nukkitcoders.mobplugin.entities.BaseEntity.attack(BaseEntity.java:173) ~[?:?]                                                                               
        at cn.nukkit.Player.handleDataPacket(Player.java:3211) ~[nukkit-1.0-SNAPSHOT.jar:?]                                                                            
        at java.util.ArrayList.forEach(ArrayList.java:1257) [?:1.8.0_242]                                                                                              
        at cn.nukkit.network.Network.processPackets(Network.java:197) [nukkit-1.0-SNAPSHOT.jar:?]                                                                      
        at cn.nukkit.network.Network.processBatch(Network.java:180) [nukkit-1.0-SNAPSHOT.jar:?]                                                                        
        at cn.nukkit.Player.handleDataPacket(Player.java:2093) [nukkit-1.0-SNAPSHOT.jar:?]                                                                             
        at cn.nukkit.network.RakNetInterface.handleEncapsulated(RakNetInterface.java:157) [nukkit-1.0-SNAPSHOT.jar:?]                                                  
        at cn.nukkit.raknet.server.ServerHandler.handlePacket(ServerHandler.java:132) [nukkit-1.0-SNAPSHOT.jar:?]                                                      
        at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:66) [nukkit-1.0-SNAPSHOT.jar:?]                                                              
        at cn.nukkit.network.Network.processInterfaces(Network.java:83) [nukkit-1.0-SNAPSHOT.jar:?]                                                                    
        at cn.nukkit.Server.tick(Server.java:1126) [nukkit-1.0-SNAPSHOT.jar:?]                                                                                         
        at cn.nukkit.Server.tickProcessor(Server.java:905) [nukkit-1.0-SNAPSHOT.jar:?]                                                                                 
        at cn.nukkit.Server.start(Server.java:882) [nukkit-1.0-SNAPSHOT.jar:?]                                                                                         
        at cn.nukkit.Server.<init>(Server.java:567) [nukkit-1.0-SNAPSHOT.jar:?]                                                                                        
        at cn.nukkit.Nukkit.main(Nukkit.java:112) [nukkit-1.0-SNAPSHOT.jar:?]                                                                                          
Caused by: java.lang.ClassCastException: nukkitcoders.mobplugin.entities.monster.walking.Skeleton cannot be cast to cn.nukkit.Player                                   
        at com.steve.nukkit.AfterLife.events.CustomEvent.onEvent(CustomEvent.java:28) ~[?:?]                                                                           
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_242]                                                                                  
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_242]                                                                
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_242]                                                        
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_242]                                                                                             
        at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:29) ~[nukkit-1.0-SNAPSHOT.jar:?]                                                      
        ... 19 more                                                                                                                                                    
```
Do you have any any guidance? Did i skip an installation or configuration step?

**Comment by Atm85** [comment]
> Do you have any any guidance? Did i skip an installation or configuration step?

Nope, the error is my problem, it thinks that the skeleton is a player when its not... ill role out a fix soon!

**Comment by lurk24** [comment]
i think i saw the same error with pigs, and pretty much every mob i tried to attack.
i will try to gather more logs in case it helps

**Comment by Atm85** [comment]
Not necessary, I know what I have to do in order to fix these errors.

**Comment by Atm85** [comment]
@lurk24 try this, i don't have mobs enabled on my server so i couldn't test, but this should have fixed it...
[AfterLife-2.2.2.zip](https://github.com/TimelessMC/Afterlife/files/4143152/AfterLife-2.2.2.zip)

**Comment by lurk24** [comment]
Awesome, thanks, no more errors when attacking mobs, but i am still seeing this when i connect (i think i forgot to mention this one):

```
20:19:38 [INFO ] LURK24tv[/12.34.56.78:51138] logged in with entity id 1 at (world, 147.3521, 67.0, 218.2524)       
20:19:39 [FATAL] Could not pass event "cn.nukkit.event.player.PlayerJoinEvent" to "AfterLife v2.2.2": null on com.steve.nukkit.AfterLife.events.JoinEvent                                                                                   
20:19:39 [ERROR] Throwing                                                                                             
cn.nukkit.utils.EventException: null                                                                                  
        at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:34) ~[nukkit-1.0-SNAPSHOT.jar:?]     
        at cn.nukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:56) ~[nukkit-1.0-SNAPSHOT.jar:?]     
        at cn.nukkit.plugin.PluginManager.callEvent(PluginManager.java:546) [nukkit-1.0-SNAPSHOT.jar:?]               
        at cn.nukkit.Player.doFirstSpawn(Player.java:887) [nukkit-1.0-SNAPSHOT.jar:?]                                 
        at cn.nukkit.Player.sendNextChunk(Player.java:839) [nukkit-1.0-SNAPSHOT.jar:?]                                
        at cn.nukkit.Player.checkNetwork(Player.java:1852) [nukkit-1.0-SNAPSHOT.jar:?]                                
        at cn.nukkit.Server.tick(Server.java:1140) [nukkit-1.0-SNAPSHOT.jar:?]                                        
        at cn.nukkit.Server.tickProcessor(Server.java:905) [nukkit-1.0-SNAPSHOT.jar:?]                                
        at cn.nukkit.Server.start(Server.java:882) [nukkit-1.0-SNAPSHOT.jar:?]                                        
        at cn.nukkit.Server.<init>(Server.java:567) [nukkit-1.0-SNAPSHOT.jar:?]                                       
        at cn.nukkit.Nukkit.main(Nukkit.java:112) [nukkit-1.0-SNAPSHOT.jar:?]                                         
Caused by: java.lang.IllegalArgumentException: state should be: databaseName is not empty                             
        at com.mongodb.assertions.Assertions.isTrueArgument(Assertions.java:99) ~[?:?]                                
        at com.mongodb.MongoNamespace.checkDatabaseNameValidity(MongoNamespace.java:59) ~[?:?]                        
        at com.mongodb.client.internal.MongoDatabaseImpl.<init>(MongoDatabaseImpl.java:70) ~[?:?]                     
        at com.mongodb.MongoClient.getDatabase(MongoClient.java:552) ~[?:?]                                           
        at NukkitDB.NukkitDB.getDatabase(NukkitDB.java:125) ~[?:?]                                                    
        at NukkitDB.NukkitDB.query(NukkitDB.java:46) ~[?:?]                                                           
        at com.steve.nukkit.AfterLife.handler.Mongodb.query(Mongodb.java:20) ~[?:?]                                   
        at com.steve.nukkit.AfterLife.events.JoinEvent.onJoin(JoinEvent.java:30) ~[?:?]                               
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_242]                                 
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_242]               
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_242]       
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_242]                                            
        at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:29) ~[nukkit-1.0-SNAPSHOT.jar:?]     
        ... 10 more                                                                                                   
20:19:39 [INFO ] LURK24tv is here! Let's party!
```

should i file a separate bug for that?

**Comment by lurk24** [comment]
hmmmm, i think the reason for the last error i posted was due to not filling in a database name or collection name in the config.yml

```
Caused by: java.lang.IllegalArgumentException: state should be: databaseName is not empty                             
```

thanks for all your help!
